MultiplicationTable/MultiplicationTable/Controllers/TableController.cs
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MultiplicationTable.Models;

namespace MultiplicationTable.Controllers
{
    /// <summary>
    /// This controller is one of the program controllers that it works on everything for 
    /// designing the multiplication table involving page designing, table designing and 
    /// manipulating, inputs and outputs controling and the related pages views.
    /// </summary>
    public class TableController : Controller
    {

        /// <summary>
        /// This action is the main action of Table controller.
        /// It shows the initiliezed page of the Table controller.
        /// </summary>
        /// <remarks>
        /// This action is a Get type. It is called by clicking on the Multiplication-Table tab.
        /// </remarks>
        /// <returns>
        /// This action returns an object of the Table class and a matrix of the computed 
        /// components of the multiplication table.
        /// </returns>
        [HttpGet]
        public ActionResult Index()
        {
            //Use try-catch block to check of throwing an exception because of an error.
            try
            {
                //Instantiate an object of the Table class using the initilized variables.
                Table table = new Table(10, "decimal");

                //Compute the multiplication table for the first time.
                MultiplicationMatrix multiplicationMatrix = new MultiplicationMatrix(table);

                //Save some variables for transfering them to the view.
                ViewData["table"] = table;
                ViewData["matrix"] = multiplicationMatrix.matrixComponents;
            }
            catch (InvalidDataException ex)
            {
                //Make a message and a javascript alert function when we have a thrown exception.
                //This function will show an error message to user on the client side.
                string message = "<script>alert('Error in input data: " + ex.Message
                    + "');</script>";

                //Write the javascript function in the client side (Fron-End) of the program.
                Response.WriteAsync(message);
            }
            return View();
        }

        /// <summary>
        /// This action works on getting some variables from the view, instantiating an 
        /// object of the Table class, computing the multiplication table and transfering some 
        /// variables to the view, and also shows the multiplication-table page.
        /// </summary>
        /// <remarks>
        /// This action is a Post type  and is called by submitting the form in the view page.
        /// </remarks>
        /// <param name="tableIn"> An object of the Table class with two variables.</param>
        /// <returns>
        /// This action returns an object of the Table class and a matrix of the computed 
        /// components of the multiplication table.
        /// </returns>
        [HttpPost]
        public ActionResult Index(Table tableIn)
        {
            //Use try-catch block to check of throwing an exception because of an error.
            try
            {
                //Instantiate an object of the Table class using the variables coming from the view.
                Table table = new Table(tableIn.MatrixSize, tableIn.MatrixBase);

                //Compute the multiplication table using the variables coming from the view.
                MultiplicationMatrix multiplicationMatrix = new MultiplicationMatrix(table);

                //Save some variables for transfering them to the view.
                ViewData["table"] = table;
                ViewData["matrix"] = multiplicationMatrix.matrixComponents;
            }
            catch (InvalidDataException ex)
            {
                //Make a message and a javascript alert function when we have a thrown exception.
                //This function will show an error message to user on the client side.
                string message = "<script>alert('Error in input data: " + ex.Message
                    + "');</script>";

                //Write the javascript function in the client side (Fron-End) of the program.
                Response.WriteAsync(message);
            }
            return View();
        }

        /// <summary>
        /// This action works on getting some variables from the view, instantiating an 
        /// object of the Table class, compute the multiplication table and transfering some 
        /// variables to the view, and also show the multiplication-table page.
        /// </summary>
        /// <remarks>
        /// This action is a Get type and is called by selecting the multiplication-table 
        /// in the view page.
        /// </remarks>
        /// <param name="size"> The size of the multiplication table.</param>
        /// <param name="mbase"> The base of the multiplication table.</param>
        /// <returns>
        /// This action returns an object of the Table class and a matrix of the computed 
        /// components of the multiplication table.
        /// </returns>
        [HttpGet]
        public ActionResult Index1(int size, string mbase)
        {
            //Use try-catch block to check of throwing an exception because of an error.
            try
            {
                //Instantiate an object of the Table class using the variables coming from the view.
                Table table = new Table(size, mbase);

                //Compute the multiplication table using the variables coming from the view.
                MultiplicationMatrix multiplicationMatrix = new MultiplicationMatrix(table);

                //Save some variables for transfering them to the view.
                ViewData["table"] = table;
                ViewData["matrix"] = multiplicationMatrix.matrixComponents;
            }
            catch (InvalidDataException ex)
            {
                //Make a message and a javascript alert function when we have a thrown exception.
                //This function will show an error message to user on the client side.
                string message = "<script>alert('Error in input data: " + ex.Message
                    + "');</script>";

                //Write the javascript function in the client side (Fron-End) of the program.
                Response.WriteAsync(message);
            }
            return View("~/Views/Table/Index.cshtml");
        }
    }
}

MultiplicationTable/MultiplicationTable/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MultiplicationTable</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MultiplicationTable</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Table" asp-action="Index">MultiPlication Table</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MultiplicationTable - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
    @RenderSection("Styles", required: false)
</body>
</html>